### ISSUE TITLE
Unable to perform Multiple Join

### ISSUE THREAD

**Issue by rajatnesto** [frappe/insights#113]
1. I'm Only able to perform single JOIN using the UI. Need to select more than 2 Tables in Insights for creating a Report.
2. The Visualization is not getting saved, and gets Bars selected and working by Default.

**Comment by nextchamp-saqib** [comment]
You should be able to join more than 2 tables

<img width="1440" alt="CleanShot 2023-04-24 at 15 25 55@2x" src="https://user-images.githubusercontent.com/25369014/233963778-9e681923-30d9-4bd2-9aae-6a6f0197be83.png">

ref: [docs](https://docs.frappeinsights.com/query/joining-data.html#joining-multiple-tables)

> The Visualization is not getting saved, and gets Bars selected and working by Default.

Can you explain with an example and/or screenshots?

**Comment by rajatnesto** [comment]
This is the JOIN i have created
<img width="950" alt="image" src="https://user-images.githubusercontent.com/120168522/234008189-06e03a85-8873-4089-9572-4d57109eb695.png">

and When i try to select the new table for an additional join
<img width="958" alt="image" src="https://user-images.githubusercontent.com/120168522/234008495-a97590bd-63e2-4bf7-8427-8eeb273bb084.png">

Not able to use any other table.

**Comment by nextchamp-saqib** [comment]
Yes, that's fine. To join any other table, you have to select some existing table

Eg.
- You already have joined Sales Invoice with Customer.
- Now to join for example Address, you have to select Sales Invoice _again_ and then select the Address inside the 2nd row as Right Table

I know it sounds confusing, but this is so that a user doesn't incorrectly join any two tables. It has to be in a proper order to generate proper SQL query
