### ISSUE TITLE
Unable to select Column with Number type in Bar chart

### ISSUE THREAD

**Issue by zeel-codder** [frappe/insights#157]
I'm trying to create a bar chart using the `Todo` DocType from `idx`->` Count of Records with given idx`. But In the x-axis, I am unable to select any of the given columns.

Version: `develop`

I have attached the screenshot for the same

- Query

<img width="1403" alt="Screenshot 2023-08-17 at 4 30 55 PM" src="https://github.com/frappe/insights/assets/69882648/19fef045-0cfc-4bc9-8609-5fc5a78ab205">

- Plot

<img width="674" alt="Screenshot 2023-08-17 at 4 31 17 PM" src="https://github.com/frappe/insights/assets/69882648/078c53d6-93aa-43ab-8d3e-7734b3578333">

**Comment by nextchamp-saqib** [comment]
Hey, I cannot see the query screenshot, can you post it again?

**Comment by zeel-codder** [comment]
Check now

**Comment by nextchamp-saqib** [comment]
Since `Group by idx` is a number field, it is only available on Y axis
To overwrite this, you need to cast it to a string field. To do that you need to add a column expression to group by idx like so,

![CleanShot 2023-08-24 at 14 48 32@2x](https://github.com/frappe/insights/assets/25369014/2192515a-2fb4-49ad-adf2-439a3f499bf2)
