### ISSUE TITLE
Is this released? Which branch is production-ready?

### ISSUE THREAD

**Issue by casesolved-co-uk** [frappe/insights#174]
Is this released?

I've installed v1.2.0 from the `main` branch assuming it was production ready and released, but there appear to be some major problems. Should I be using `marketplace` or `develop` perhaps?

There appear to be 3 versions:
- 1.0.1 marketplace
- 1.1.3 develop!?
- 1.2.0 main

Here's what I found in 30 mins:

- Install: doesn't do a frappe version dependency check. Won't work on anything before frappe v14.33 and requires node v16
- Console log full of errors
- Internal Server Errors just doing simple things, like the visual query builder automatically adds any aggregation columns to the select field list without telling you, but just gives an Internal Server Error if you also add it in the select list (which you will do if you know SQL), and you have to open the console log to find out what the problem is
- The Classic Query interface
    - no way to save columns. Appears there's an Apply button missing? See screenshot
    - could only add one table multiple times, appears the Select a table search box has a bug
- Bar Chart render problem, see screenshot
- Although you can specify a visualisation for a query, it appears you have to specify it again in the dashboard?

I appreciate the effort but this has been around for a while and I expected it to be more stable by now?

![Screen Shot 2023-09-30 at 22 00 56](https://github.com/frappe/insights/assets/110036763/32d49d26-e286-45ee-960d-878eff1df5e3)

![Screen Shot 2023-09-30 at 22 03 46](https://github.com/frappe/insights/assets/110036763/4b71266d-d605-4f4c-9124-be65ae13db33)

Edit: previous versions don't seem any better

**Comment by nextchamp-saqib** [comment]
> The Classic Query interface
no way to save columns. Appears there's an Apply button missing? See screenshot
could only add one table multiple times, appears the Select a table search box has a bug

This interface should be stable to use. The Apply button can be found once you scroll the column/filter section.
I'll fix the scrollbars or make the apply button sticky.

The visual query was stable when I checked on fast Internet connection
Due to autosave, the visual query builder becomes flaky because of slow connection
I am working on it.

Rest everything should be pretty much stable

Thanks for the critical feedback

**Comment by casesolved-co-uk** [comment]
Thanks for the feedback but I can't recommend this to my customer as it is. Back to Power BI 😕

**Comment by nextchamp-saqib** [comment]
Will get there 🙂
