### ISSUE TITLE
Label of column not visible in Bar Chart

### ISSUE THREAD

**Issue by michellealva** [frappe/insights#37]
![Screenshot 2022-10-15 at 10 49 21 AM](https://user-images.githubusercontent.com/50285544/195970214-1d877f46-160d-4f50-beaa-53212ccfa2d4.png)

**Comment by nextchamp-saqib** [comment]
Fixed with 52c354d176b30a1182bddfe0e2f39dde02d63d93

---
Labels were skipped when they overlapped with others
Now, labels won't be skipped, but by default, they will overlap.
To avoid the overlap, you will have to **rotate the labels** or **switch X and Y axis** for more space.

**Rotate Label Eg.**
<img width="567" alt="CleanShot 2022-10-31 at 17 20 25@2x" src="https://user-images.githubusercontent.com/25369014/199001808-12541d32-0203-4c2c-b171-39b7ead28040.png">
