### ISSUE TITLE
Avg function should not round off the result

### ISSUE THREAD

**Issue by michellealva** [frappe/insights#66]
or give the option to choose roundoff, but this shouldn't be the default behaviour

**Comment by nextchamp-saqib** [comment]
problem eg.

support rating field in a support ticket record, the values could be 5, 4, 3, 4, 5, etc.
since these fields are integer values, the column is formatted as an integer, so the avg(`rating`) would also be formatted as an integer. If the same column is added with expression, with the decimal format, then it shows decimals
